FRANKENSTEINS_AUTOML_TOPIC = "FRANKENSTEINS_AUTOML"
MCTS_TOPIC = "MCTS"
OPTIMIZATION_TOPIC = "OPTIMIZATION"
SEARCH_GRAPH_TOPIC = "SEARCH_GRAPH"

ALL_TOPICS = [
    FRANKENSTEINS_AUTOML_TOPIC,
    MCTS_TOPIC,
    OPTIMIZATION_TOPIC,
    SEARCH_GRAPH_TOPIC,
]
